apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  creationTimestamp: null
  name: cd-deploy-from-push-pipeline
  namespace: chetan-cicd-environment
spec:
  resources:
  - name: source-repo
    type: git
  tasks:
  - name: apply-source
    params:
    - name: NAMESPACE
      value: cicd-environment
    resources:
      inputs:
      - name: source
        resource: source-repo
    taskRef:
      kind: Task
      name: deploy-from-source-task
---
