apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: cicd-event-listener
  name: github-webhook-event-listener
  namespace: chetan-cicd-environment
spec:
  host: ""
  port:
    targetPort: 8080
  subdomain: ""
  to:
    kind: Service
    name: el-cicd-event-listener
    weight: 100
  wildcardPolicy: None
---
