apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: app-ci-template
  namespace: chetan-cicd-environment
spec:
  params:
  - description: The git branch for this PR
    name: gitref
  - description: the specific commit SHA.
    name: gitsha
  - description: The git repository url
    name: gitrepositoryurl
  - description: The GitHub repository for this PullRequest.
    name: fullname
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      creationTimestamp: null
      name: app-ci-pipeline-run-$(uid)
    spec:
      params:
      - name: REPO
        value: $(params.fullname)
      - name: COMMIT_SHA
        value: $(params.gitsha)
      pipelineRef:
        name: app-ci-pipeline
      resources:
      - name: source-repo
        resourceSpec:
          params:
          - name: revision
            value: $(params.gitref)
          - name: url
            value: $(params.gitrepositoryurl)
          type: git
      - name: runtime-image
        resourceSpec:
          params:
          - name: url
            value: quay.io/cbanavik/taxi:$(params.gitref)-$(params.gitsha)  # app-image-registry will be added here
          type: image
      serviceAccountName: pipeline
    status: {}
status: {}